MathDemystified-Django/mathdem/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views 
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('notes/', include('notes.urls')),
    path('questions/', include('questions.urls'))



]

MathDemystified-Django/notes/urls.py
from django.urls import path
from .import views

app_name = 'notes'
urlpatterns = [
    path('', views.notes_list, name="list"),
    path('plusone/', views.plusone, name="plusone"),
    path('plustwo/', views.plustwo, name="plustwo"),
    path('linearalgebra/', views.linearalgebra, name="linearalgebra"),
    path('<slug:slug>', views.notespage, name="page"),


  
]

MathDemystified-Django/questions/urls.py
from django.urls import path
from .import views

app_name = 'questions'
urlpatterns = [
    path('', views.questions_list, name="list"),

]

MathDemystified-Django/notes/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.title

MathDemystified-Django/questions/models.py
from django.db import models

# Create your models here.

MathDemystified-Django/mathdem/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html' )

MathDemystified-Django/notes/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.

def notes_list(request):
        return render(request, 'notes_list.html')

def plusone(request):
        return render(request, 'plusone.html')

def plustwo(request):
        return render(request, 'plustwo.html')


def linearalgebra(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'linearalgebra.html', { 'posts': posts})

def notespage(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'notespage.html', { 'post': post})

MathDemystified-Django/questions/views.py
from django.shortcuts import render

# Create your views here.

def questions_list(request):
        return render(request, 'questions_list.html')

MathDemystified-Django/notes/templates/linearalgebra.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
 
Linear Algebra  

{% endblock %}



{% block content %}


<div class="container align-items-center">
    <div class="row mb-2">
        {% for post in posts%}

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0"> {{ post.title}} </h3>
            <a href="{% url 'notes:page' slug=post.slug %}" class="stretched-link">View</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

        {% endfor %}

      


    </div>
    
  </div>

{% endblock %}

MathDemystified-Django/notes/templates/notes_list.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
 
Notes 

{% endblock %}



{% block content %}

<div class="container">
    <div class="row mb-2">
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary-emphasis"
              >HSE
            </strong>
            <h3 class="mb-0">Class 11 SCERT</h3>

            <p class="card-text mb-auto">
              HIgher Secondary Class 11 notes based on the latest Kerala Scert
              Syllabus.
            </p>
            <a
              href="{% url "notes:plusone" %}"
              class="icon-link gap-1 icon-link-hover stretched-link"
            >
              Download Notes
              <img src="{% static 'images/chevron-right.svg' %}" alt="" />
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
            <img src="{% static "images/11pic.jpg" %}" width="200px" height="250px" alt="">

          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success-emphasis"
              >HSE</strong
            >
            <h3 class="mb-0">Class 12 SCERT</h3>
            <p class="mb-auto">
              HIgher Secondary Class 12 notes based on the latest Kerala Scert
              Syllabus.
            </p>
            <a
              href="{% url "notes:plustwo" %}"
              class="icon-link gap-1 icon-link-hover stretched-link"
            >
              Download Notes
              <img src="{% static "images/chevron-right.svg" %}" alt="" />
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
            <img src="{% static "images/12pic.jpg" %}" width="200px" height="250px" alt="">
          </div>
        </div>
      </div>


      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success-emphasis"
              >UG/PG</strong
            >
            <h3 class="mb-0">Linear Algebra </h3>
            <p class="mb-auto">
              UG/PG linear algebra random notes 
            </p>
            <a
              href="{% url "notes:linearalgebra" %}"
              class="icon-link gap-1 icon-link-hover stretched-link"
            >
              View Notes
              <img src="{% static "images/chevron-right.svg" %}" alt="" />
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
            <img src="{% static "images/12pic.jpg" %}" width="200px" height="250px" alt="">
          </div>
        </div>
      </div>


    </div>
  </div>

    

{% endblock %}

MathDemystified-Django/notes/templates/notespage.html
{% extends 'layout.html' %}

{% block title %}
 
{{ post.title }}

{% endblock %}



{% block content %}

<section>

        <h1>{{post.title}}</h1>
        <p>{{  post.date }}</p>
        <p>{{ post.body }}</p>


</section>
{% endblock %}

MathDemystified-Django/notes/templates/plusone.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
 
Plus One 

{% endblock %}



{% block content %}
<div class="container align-items-center">
    <div class="row mb-2">
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Sets</h3>
            <a href="{% static 'pdfs/notes/11/sets.pdf' %}" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Relations and Functions</h3>
            <a href="{% static 'pdfs/notes/11/relations.pdf' %}" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Triganometric Functions</h3>
            <a href="./pdf/11/triganometry.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Complex Numbers and Quadratic Equations</h3>
            <a href="./pdf/11/complex.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Linear Inequalities</h3>
            <a href="./pdf/11/linear.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Permutations and Combinations</h3>
            <a href="./pdf/11/probability.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Binomial Theorem</h3>
            <a href="./pdf/11/probability.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Sequences and Series</h3>
            <a href="./pdf/11/sequence.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Straight Lines</h3>
            <a href="./pdf/11/straight .pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Conic Sections</h3>
            <a href="./pdf/11/conic.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Introduction to Three Dimensional Geometry</h3>
            <a href="./pdf/11/3d.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Limits and Derivatives</h3>
            <a href="./pdf/11/limts.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Statitics</h3>
            <a href="./pdf/11/statitics.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Probability</h3>
            <a href="./pdf/11/probability.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>


    </div>
  </div>



{% endblock %}

MathDemystified-Django/notes/templates/plustwo.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
 
Plus Two 

{% endblock %}


{% block content %}

<div class="container align-items-center">
    <div class="row mb-2">

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Relations and Functions</h3>
            <a href="{% static 'pdfs/notes/11/sets.pdf' %}" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Inverse Triganometric Functions</h3>
            <a href="./pdf/12/main.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Matrices</h3>
            <a href="./pdf/12/matrices.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Determinants</h3>
            <a href="./pdf/12/determinants.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Continuity and Differentiability</h3>
            <a href="./pdf/12/contanddiff.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Application of Derivatives</h3>
            <a href="./pdf/12/applicationofderivatives.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Integrals</h3>
            <a href="./pdf/12/integrals.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Application of Integrals</h3>
            <a href="./comingsoon.html" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Differential Equations</h3>
            <a href="./comingsoon.html" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Vector Algebra</h3>
            <a href="./pdf/12/vector.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Three Dimensional Geometry</h3>
            <a href="./pdf/12/threedimensional.pdf" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Linear Programming</h3>
            <a href="./comingsoon.html" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static bg-light">
            <h3 class="mb-0">Probability</h3>
            <a href="./comingsoon.html" class="stretched-link">Download</a>
          </div>
          <div class="col-auto d-none d-lg-block"></div>
        </div>
      </div>


    </div>
  </div>




{% endblock %}

MathDemystified-Django/questions/templates/questions_list.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
 
Notes 

{% endblock %}



{% block content %}
<div class="container">
    <div class="row mb-2">
      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary-emphasis"
              >HSE
            </strong>
            <h3 class="mb-0">Class 11 SCERT</h3>

            <p class="card-text mb-auto">
              HIgher Secondary Class 11 Questions based on the latest Kerala Scert
              Syllabus.
            </p>
            <a
              href="./questions/class11.html"
              class="icon-link gap-1 icon-link-hover stretched-link"
            >
              View Questions
              <img src="{% static "images/chevron-right.svg" %}" alt="" />
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
            <img src="{% static "images/11pic.jpg" %}" width="200px" height="250px" alt="">

          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div
          class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
        >
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success-emphasis"
              >HSE</strong
            >
            <h3 class="mb-0">Class 12 SCERT</h3>
            <p class="mb-auto">
              HIgher Secondary Class 12 Questions based on the latest Kerala Scert
              Syllabus.
            </p>
            <a
              href="./questions/class12.html"
              class="icon-link gap-1 icon-link-hover stretched-link"
            >
              View Questions
              <img src="{% static "images/chevron-right.svg" %}" alt="" />
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
<img src="{% static "images/12pic.jpg" %}" width="200px" height="250px" alt="">
          </div>
        </div>
      </div>
    </div>
  </div>
    

{% endblock %}

MathDemystified-Django/templates/about.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
Home 

{% endblock %}



{% block content %}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">About</h1>
        <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

{% endblock %}

MathDemystified-Django/templates/contact.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
Home 

{% endblock %}



{% block content %}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Contact 
        </h1>
        <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>
    

{% endblock %}

MathDemystified-Django/templates/home.html
{% extends 'layout.html' %}

{% load static %}
{% block title %}
Home 

{% endblock %}


{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="{% static 'images/infinitygif.gif' %}" alt="" width="150" height="150">
    <h1 class="display-5 fw-bold text-body-emphasis">Math Demystified</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Let's demystify the magic of numbers and unleash your inner mathematician!.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
       <a href="./pages/notes.html"><button type="button" class="btn btn-primary btn-lg px-4 gap-3" >Notes</button> </a> 
        <a href="./pages/Questions.html"><button type="button" class="btn btn-outline-secondary btn-lg px-4">Questions</button></a>
      </div>
    </div>
  </div>



{% endblock %}

MathDemystified-Django/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %}

        Django App
        {% endblock %}

    </title>

    <style>
        {% block style %}


        {% endblock %}
    </style>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />


    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
      </script>
      <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
      </script>

  </head>
  <body  >
    <div class="container">
      <header
        class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom"
      >
        <a
          href="{% url 'home' %}"
          class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
        >
          <img src="{% static 'images/hexagon-half.svg' %}" alt="" width="40" />
          <span class="fs-4"> Math Demystified</span>
        </a>

        <ul class="nav nav-pills">
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link " aria-current="page"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a href="{% url 'notes:list' %}" class="nav-link ">Notes</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'questions:list' %}" class="nav-link ">Question Papers</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'about' %}" class="nav-link">About</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'contact' %}" class="nav-link">Contact</a>
          </li>
        </ul>
      </header>
    </div>

    <div class="container  text-center">

  

        {% block content %}


        {% endblock %}
     
    
    </div>

    <div class="container">
      
      <footer  class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3" style="margin-bottom: 0px; margin-top: 160px;">
          <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-body-secondary">About</a></li>
          <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link px-2 text-body-secondary">Contact</a></li>
        </ul>
      </footer>
    </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<script src="{% static 'js/background_objects.js' %}"></script>
</body>
</body>

</html>
    


    
    